INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(1,'jodin','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(2,'leymarie','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(3,'koenig','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(4,'rihet','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(5,'bissey','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(6,'pelletier','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(7,'legoux','a','a','a');
INSERT INTO DEMANDE_INSCRIPTION(ID_JOUEUR,NOM,PRENOM,ADDR_POSTALE,DATE_NAISSANCE) VALUES(8,'caye','a','a','a');